### ISSUE TITLE
[PE-D] Sortclient dsc does not work

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-F10-4/tp#101]
Posted is the before and after sortedclient dsc command. No chances in the list can be seen.

![Screenshot (11).png](https://raw.githubusercontent.com/LeopardMerkava/ped/main/files/95bca506-6119-4ea8-b77b-5d1b915e92d5.png)
![Screenshot (12).png](https://raw.githubusercontent.com/LeopardMerkava/ped/main/files/82d0d17e-84bc-4b39-82ce-bd76ce0c6365.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: LeopardMerkava/ped#8

**Comment by yatbun** [comment]
Duplicate to #82
