### ISSUE TITLE
[PE-D] dsc for sortclient does not work as expected

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-F10-4/tp#115]
It produces the same output as sortclient asc - sort in alphabetical order (whereas I would expect it to sort in reverse alphabetical order)

Output after running sortclient dsc (still in alphabetical order)

![Screenshot 2021-10-29 at 4.54.56 PM.png](https://raw.githubusercontent.com/Banana3021/ped/main/files/ace44b32-84e2-4fc5-8e3d-d7870c6b0328.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Banana3021/ped#6

**Comment by yatbun** [comment]
Bug not reproducible.

**Comment by yatbun** [comment]
Duplicate to #82
