### ISSUE TITLE
[PE-D] The editpolicy command does not work

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-F10-4/tp#117]
![image.png](https://raw.githubusercontent.com/mrmrinal/ped/main/files/37ae8480-4a4e-4036-ae74-5202276f6f7b.png)

The example editpolicy command from the UG was inputted and the command does not work according the what the UG mentions

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: mrmrinal/ped#10

**Comment by yatbun** [comment]
The error lies with the UG not having the updated payment format. The feature works as intended.
