### ISSUE TITLE
[PE-D] Listpolicy not clear enough

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-F10-4/tp#123]
![image.png](https://raw.githubusercontent.com/mrmrinal/ped/main/files/ca637216-75e2-4e1b-a7f9-e65123de1553.png)

In the UG it is mentioned that the ```listpolicy``` lists all the policies, but from a UI point there was no change apart from the resultbox showing that it has listed all policies.

Perhaps it can be a bit more clear in the UG as to where the policies are listed?

Before:
 
![image.png](https://raw.githubusercontent.com/mrmrinal/ped/main/files/d7bea269-f7ba-427d-8ebf-169586afa041.png)

After:

![image.png](https://raw.githubusercontent.com/mrmrinal/ped/main/files/90544a18-4154-4bfe-83e8-1b547b080440.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: mrmrinal/ped#12

**Comment by meerian** [comment]
feature working as expected
