### ISSUE TITLE
[PE-D] sortpolicy pricedsc not working

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-F10-4/tp#128]
sortpolicy pricedsc is not sorting payments in descending order.

($300.00 is below $1.00)

![Screenshot 2021-10-29 at 5.43.03 PM.png](https://raw.githubusercontent.com/Banana3021/ped/main/files/5fb5d33b-6c10-4ef2-acd0-44597f4d48ee.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Banana3021/ped#11

**Comment by yatbun** [comment]
Duplicate to #97
