### ISSUE TITLE
Error message for expiring policy can be modified slightly

### ISSUE THREAD

**Issue by BenjaminLHR** [AY2122S1-CS2103-F10-4/tp#160]
![image](https://user-images.githubusercontent.com/48859735/140604595-4a316fff-9a2b-46cf-b67b-60c2f89222ea.png)

Technically the first policy has already expired.

**Comment by yatbun** [comment]
Can change to "Showing policies that will be expired in 1 month"

**Comment by sherrpass** [comment]
Consider updating UG to make it clear as well or change command name
