### ISSUE TITLE
Unable to add policies with same names but different details

### ISSUE THREAD

**Issue by yzhilong** [AY2122S1-CS2103-F10-4/tp#177]
![image](https://user-images.githubusercontent.com/44795294/140606211-82a72a9a-3fb7-4555-ad29-57466d1aaf66.png)

I think it is quite likely that a user has multiple policies with the same name but from different providers and different payout rates. This does not allow for it.

**Comment by sherrpass** [comment]
Update UG to make it clear that we uniquely identify policies and contacts through their names
